[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
deployment_scripts = "GMwTBSDebYGD4qGq2NKcuBhGpzaxr6AHn1u57k45mCWQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
